steps:
  # Configure Maven settings to authenticate to Artifact Registry via an access token
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'configure-maven-settings'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ACCESS_TOKEN=$(gcloud auth print-access-token)
        mkdir -p /root/.m2
        cat > /root/.m2/settings.xml << EOF
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
            <server>
              <id>gcp-maven-proxy</id>
              <username>oauth2accesstoken</username>
              <password>${ACCESS_TOKEN}</password>
            </server>
          </servers>
        </settings>
        EOF

  # Run Maven tests
  - name: 'maven:3.9-eclipse-temurin-21'
    id: 'test-backend'
    entrypoint: 'mvn'
    args: ['test']

  # Run linting (Checkstyle, SpotBugs, PMD)
  - name: 'maven:3.9-eclipse-temurin-21'
    id: 'lint-backend'
    entrypoint: 'mvn'
    args: ['verify', '-DskipTests']

  # Build the application JAR (skip on PR builds)
  - name: 'maven:3.9-eclipse-temurin-21'
    id: 'build-backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Skip build on PR builds
        if [ "$BRANCH_NAME" != "main" ]; then
          echo "PR build detected (branch: $BRANCH_NAME), skipping package step"
          echo "Build validation complete ✓"
          exit 0
        fi
        
        echo "Building application package..."
        mvn package -DskipTests

  # Build Docker image - ONLY on main branch
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Only build image on main branch
        if [ "$BRANCH_NAME" != "main" ]; then
          echo "PR build detected (branch: $BRANCH_NAME), skipping Docker build"
          exit 0
        fi
        
        echo "Building Docker image..."
        docker build -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${SHORT_SHA} \
              -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest .

  # Push Docker image - ONLY on main branch
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Only push image on main branch
        if [ "$BRANCH_NAME" != "main" ]; then
          echo "PR build detected (branch: $BRANCH_NAME), skipping Docker push"
          exit 0
        fi
        
        echo "Pushing Docker image..."
        docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${SHORT_SHA}
        docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest

  # Deploy new image to Cloud Run - ONLY on main branch
  # Note: Only updates the image, other config managed by Terraform
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Only deploy on main branch
        if [ "$BRANCH_NAME" != "main" ]; then
          echo "PR build detected (branch: $BRANCH_NAME), skipping deployment"
          exit 0
        fi
        
        echo "Deploying new image to Cloud Run..."
        gcloud run services update ${_SERVICE_NAME} \
          --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest \
          --region ${_REGION}
        
        echo "Deployment complete ✓"

# Substitutions for different environments
substitutions:
  _SERVICE_NAME: 'recipe-ai-service'
  _REGION: 'europe-west2'
  _ARTIFACT_REGISTRY_REPO: 'recipe-ai'

# Use faster machine type for builds
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout after 20 minutes
timeout: '1200s'
