steps:
  # Determine version based on branch
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'determine-version'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "Determining version for branch: $BRANCH_NAME"

        if [ "$BRANCH_NAME" = "main" ]; then
          echo "Main branch detected - using release version"
          # For main branch, get the latest tag and bump patch version
          GIT_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          # Remove 'v' prefix if present
          CLEAN_TAG=${GIT_TAG#v}
          echo "Latest tag: $CLEAN_TAG"

          # Parse version components
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CLEAN_TAG"
          NEW_PATCH=$((PATCH + 1))
          VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          echo "New version: $VERSION"
        else
          echo "Feature/PR branch detected - using current SNAPSHOT version"
          # For feature branches, use the current version from pom.xml
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          # Ensure it's a SNAPSHOT version for development
          if [[ $CURRENT_VERSION != *-SNAPSHOT ]]; then
            VERSION="${CURRENT_VERSION}-SNAPSHOT"
          else
            VERSION="$CURRENT_VERSION"
          fi
          echo "Using SNAPSHOT version: $VERSION"
        fi

        echo "Building with version: $VERSION"
        echo "$VERSION" > /workspace/version.txt

  # Set version using Maven versions plugin
  - name: 'maven:3.9-eclipse-temurin-21'
    id: 'set-version'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSION=$(cat /workspace/version.txt)
        echo "Setting Maven version to: $VERSION"
        mvn versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false  # Configure Maven settings to authenticate to Artifact Registry via an access token
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'configure-maven-settings'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p /workspace/.m2
        # Generate a minimal Maven settings.xml with server credentials for Artifact Registry
        # This avoids reliance on gcloud's print-settings subcommand which may not be available
        cat > /workspace/.m2/settings.xml <<'SETTINGS'
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
            <server>
              <id>gcp-maven-proxy</id>
              <username>oauth2accesstoken</username>
              <password>@@ACCESS_TOKEN@@</password>
            </server>
          </servers>
        </settings>
        SETTINGS
        # Replace placeholder with runtime access token (error out if token cannot be retrieved)
        # Replace placeholder in the settings.xml with a runtime access token
        sed -i "s|@@ACCESS_TOKEN@@|$(gcloud auth print-access-token)|g" /workspace/.m2/settings.xml
        # Verify the token is populated; fail if empty to avoid unauthorized Maven requests
        if ! grep -q -E "<password>[^<]+</password>" /workspace/.m2/settings.xml; then
          echo "ERROR: settings.xml not properly configured with access token"
          exit 1
        fi

  # Run Maven tests
  - name: 'maven:3.9-eclipse-temurin-21'
    id: 'test-backend'
    entrypoint: 'mvn'
    args:
      - '-s'
      - '/workspace/.m2/settings.xml'
      - 'test'

  # Run linting (Checkstyle, SpotBugs, PMD)
  - name: 'maven:3.9-eclipse-temurin-21'
    id: 'lint-backend'
    entrypoint: 'mvn'
    args:
      - '-s'
      - '/workspace/.m2/settings.xml'
      - 'verify'
      - '-DskipTests'

  # Build the application JAR (CI builds artifact for Docker image; runs for PRs too)
  - name: 'maven:3.9-eclipse-temurin-21'
    id: 'build-backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSION=$(cat /workspace/version.txt)
        echo "Building application package with version: $VERSION"
        mvn -s /workspace/.m2/settings.xml package -DskipTests

  # Build Docker image - ONLY on main branch
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Building Docker image..."
        docker build -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${SHORT_SHA} \
              -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest .

  # Push Docker image - ONLY on main branch
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Only push image on main branch
        if [ "$BRANCH_NAME" != "main" ]; then
          echo "PR build detected (branch: $BRANCH_NAME), skipping Docker push"
          exit 0
        fi
        
        echo "Pushing Docker image..."
        docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${SHORT_SHA}
        docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest

  # Deploy new image to Cloud Run - ONLY on main branch
  # Note: Only updates the image, other config managed by Terraform
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Only deploy on main branch
        if [ "$BRANCH_NAME" != "main" ]; then
          echo "PR build detected (branch: $BRANCH_NAME), skipping deployment"
          exit 0
        fi
        
        echo "Deploying new image to Cloud Run..."
        gcloud run services update ${_SERVICE_NAME} \
          --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest \
          --region ${_REGION}
        
        echo "Deployment complete ✓"

  # Tag the release after successful deployment - ONLY on main branch
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'tag-release'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Only tag on main branch after successful deployment
        if [ "$BRANCH_NAME" != "main" ]; then
          echo "PR build detected (branch: $BRANCH_NAME), skipping tagging"
          exit 0
        fi
        
        VERSION=$(cat /workspace/version.txt)
        TAG_NAME="v$VERSION"
        
        echo "Creating git tag: $TAG_NAME"
        git config --global user.email "ci@recipe-management.com"
        git config --global user.name "CI Bot"
        
        # Create and push the tag
        git tag $TAG_NAME
        git push origin $TAG_NAME
        
        echo "Release tagged: $TAG_NAME"

# Substitutions for different environments
substitutions:
  _SERVICE_NAME: 'recipe-ai-service'
  _REGION: 'europe-west2'
  _ARTIFACT_REGISTRY_REPO: 'recipe-ai'

# Use faster machine type for builds
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout after 20 minutes
timeout: '1200s'
