steps:  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'check-concurrent-builds'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Only check for concurrent builds on main branch
        if [ "$BRANCH_NAME" != "main" ]; then
          echo "Feature/PR build detected, skipping concurrent build check"
          exit 0
        fi

        echo "Checking for concurrent builds on main branch..."

        # Simple approach: check if any builds are currently running
        # Since this step only runs on main branch, any running builds indicate concurrency
        echo "Running gcloud builds list command..."
        if ! RUNNING_BUILDS=$(gcloud builds list \
          --filter="status:(PENDING OR WORKING)" \
          --format="value(id)" \
          --limit=1 2>&1); then
          echo "WARNING: gcloud builds list failed: $RUNNING_BUILDS"
          echo "Skipping concurrent build check due to gcloud error"
          exit 0
        fi

        RUNNING_COUNT=$(echo "$RUNNING_BUILDS" | wc -l)
        echo "gcloud command output: $RUNNING_BUILDS"
        echo "Running builds count: $RUNNING_COUNT"

        if [ "$RUNNING_COUNT" -gt 0 ]; then
          echo "ERROR: Found $RUNNING_COUNT concurrent build(s) running."
          echo "Listing current builds for debugging:"
          gcloud builds list \
            --filter="status:(PENDING OR WORKING)" \
            --format="table(id,status,createTime)" \
            --limit=3
          echo "Failing this build to prevent concurrent deployments."
          exit 1
        fi

        echo "No concurrent builds found ✓"
  - name: 'maven:3.9-eclipse-temurin-21'
    id: 'determine-version'
    entrypoint: 'bash'
    args:
      - '-c'
      - |

        if [ "$BRANCH_NAME" = "main" ]; then
          echo "Main branch build detected - bumping patch version for release"
          # Use version.sh script to bump patch version
          cd /workspace
          chmod +x version.sh
          ./version.sh bump-patch
          VERSION=$$(./version.sh current | sed 's/Current version: //')
          echo "New release version: $${VERSION}"
        else
          echo "Feature/PR branch build detected - ensuring SNAPSHOT version"
          # For feature branches, ensure version has SNAPSHOT suffix
          cd /workspace
          chmod +x version.sh
          ./version.sh add-snapshot
          VERSION=$$(./version.sh current | sed 's/Current version: //')
          echo "Using SNAPSHOT version: $${VERSION}"
        fi

        echo "Building with version: $${VERSION}"
        # Save version for use in subsequent steps
        echo "$${VERSION}" > /workspace/.build_version
        # Version is already set in pom.xml by version.sh script
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'configure-maven-settings'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p /workspace/.m2
        # Generate a minimal Maven settings.xml with server credentials for Artifact Registry
        # This avoids reliance on gcloud's print-settings subcommand which may not be available
        cat > /workspace/.m2/settings.xml <<'SETTINGS'
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
            <server>
              <id>gcp-maven-proxy</id>
              <username>oauth2accesstoken</username>
              <password>@@ACCESS_TOKEN@@</password>
            </server>
          </servers>
        </settings>
        SETTINGS
        # Replace placeholder with runtime access token (error out if token cannot be retrieved)
        # Replace placeholder in the settings.xml with a runtime access token
        sed -i "s|@@ACCESS_TOKEN@@|$(gcloud auth print-access-token)|g" /workspace/.m2/settings.xml
        # Verify the token is populated; fail if empty to avoid unauthorized Maven requests
        if ! grep -q -E "<password>[^<]+</password>" /workspace/.m2/settings.xml; then
          echo "ERROR: settings.xml not properly configured with access token"
          exit 1
        fi

  # Run Maven tests
  - name: 'maven:3.9-eclipse-temurin-21'
    id: 'test-backend'
    entrypoint: 'mvn'
    args:
      - '-s'
      - '/workspace/.m2/settings.xml'
      - '-Dmaven.repo.local=/workspace/.m2/repo'
      - 'test'

  # Run linting (Checkstyle, SpotBugs, PMD)
  - name: 'maven:3.9-eclipse-temurin-21'
    id: 'lint-backend'
    entrypoint: 'mvn'
    args:
      - '-s'
      - '/workspace/.m2/settings.xml'
      - '-Dmaven.repo.local=/workspace/.m2/repo'
      - 'verify'
      - '-DskipTests'

  # Build the application JAR (CI builds artifact for Docker image; runs for PRs too)
  - name: 'maven:3.9-eclipse-temurin-21'
    id: 'build-backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Building application package..."
        mvn -s /workspace/.m2/settings.xml -Dmaven.repo.local=/workspace/.m2/repo package -DskipTests

  # Build Docker image - ONLY on main branch
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |

        echo "Building Docker image..."
        cd /workspace
        VERSION=$$(cat /workspace/.build_version)
        echo "Tagging image with version: $${VERSION}"
        
        # Set variables explicitly
        REGION="${_REGION}"
        PROJECT_ID="${PROJECT_ID}"
        ARTIFACT_REGISTRY_REPO="${_ARTIFACT_REGISTRY_REPO}"
        SERVICE_NAME="${_SERVICE_NAME}"
        SHORT_SHA="${SHORT_SHA}"
        
        # Build Docker image with explicit path
        echo "Executing: docker build -t $${REGION}-docker.pkg.dev/$${PROJECT_ID}/$${ARTIFACT_REGISTRY_REPO}/$${SERVICE_NAME}:$${SHORT_SHA} -t $${REGION}-docker.pkg.dev/$${PROJECT_ID}/$${ARTIFACT_REGISTRY_REPO}/$${SERVICE_NAME}:$${VERSION} -t $${REGION}-docker.pkg.dev/$${PROJECT_ID}/$${ARTIFACT_REGISTRY_REPO}/$${SERVICE_NAME}:latest ."
        docker build \
          -t $${REGION}-docker.pkg.dev/$${PROJECT_ID}/$${ARTIFACT_REGISTRY_REPO}/$${SERVICE_NAME}:$${SHORT_SHA} \
          -t $${REGION}-docker.pkg.dev/$${PROJECT_ID}/$${ARTIFACT_REGISTRY_REPO}/$${SERVICE_NAME}:$${VERSION} \
          -t $${REGION}-docker.pkg.dev/$${PROJECT_ID}/$${ARTIFACT_REGISTRY_REPO}/$${SERVICE_NAME}:latest \
          .

  # Push Docker image - ONLY on main branch
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Only push image on main branch
        if [ "$BRANCH_NAME" != "main" ]; then
          echo "Feature/PR build detected, skipping Docker push"
          exit 0
        fi

        echo "Pushing Docker image..."
        cd /workspace
        VERSION=$$(cat /workspace/.build_version)
        
        # Set variables explicitly
        REGION="${_REGION}"
        PROJECT_ID="${PROJECT_ID}"
        ARTIFACT_REGISTRY_REPO="${_ARTIFACT_REGISTRY_REPO}"
        SERVICE_NAME="${_SERVICE_NAME}"
        SHORT_SHA="${SHORT_SHA}"
        
        docker push $${REGION}-docker.pkg.dev/$${PROJECT_ID}/$${ARTIFACT_REGISTRY_REPO}/$${SERVICE_NAME}:$${SHORT_SHA}
        docker push $${REGION}-docker.pkg.dev/$${PROJECT_ID}/$${ARTIFACT_REGISTRY_REPO}/$${SERVICE_NAME}:$${VERSION}
        docker push $${REGION}-docker.pkg.dev/$${PROJECT_ID}/$${ARTIFACT_REGISTRY_REPO}/$${SERVICE_NAME}:latest

  # Deploy new image to Cloud Run - ONLY on main branch
  # Note: Only updates the image, other config managed by Terraform
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
      
        if [ "$BRANCH_NAME" != "main" ]; then
          echo "Feature/PR build detected, skipping deployment"
          exit 0
        fi

        echo "Deploying new image to Cloud Run..."
        gcloud run services update ${_SERVICE_NAME} \
          --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest \
          --region ${_REGION}

        echo "Deployment complete ✓"

  # Prepare next development version - ONLY on main branch
  - name: 'maven:3.9-eclipse-temurin-21'
    id: 'prepare-next-version'
    entrypoint: 'bash'
    args:
      - '-c'
      - |

        if [ "$BRANCH_NAME" != "main" ]; then
          echo "Feature/PR build detected, skipping version preparation"
          exit 0
        fi

        # Prevent infinite build loops: skip if this commit was already a version bump
        if git log --oneline -1 | grep -q "Bump version"; then
          echo "This commit was already a version bump, skipping to prevent infinite loop"
          exit 0
        fi

        echo "Preparing next development version..."
        cd /workspace
        chmod +x version.sh

        # Install git if not available (Maven image may not have it)
        if ! command -v git &> /dev/null; then
          echo "Installing git..."
          apt-get update && apt-get install -y git
        fi

        # Ensure we're on the main branch and have the latest changes
        echo "Current branch before checkout: $(git branch --show-current)"
        git checkout main || git checkout -b main origin/main
        echo "Current branch after checkout: $(git branch --show-current)"
        git pull origin main

        # Bump to next SNAPSHOT version for continued development
        ./version.sh bump-patch
        ./version.sh add-snapshot

        NEXT_VERSION=$$(./version.sh current | sed 's/Current version: //')
        echo "Next development version prepared: $${NEXT_VERSION}"

        # Configure git for committing version changes
        git config --global user.email "ci@recipe-management.com"
        git config --global user.name "CI Bot"

        # Commit the version change back to main
        git add pom.xml
        git commit -m "Bump version to $${NEXT_VERSION} for next development cycle"
        
        # Push the current branch to origin/main
        echo "Pushing to origin/main..."
        git push origin HEAD:main

        echo "Version $${NEXT_VERSION} committed to main ✓"
substitutions:
  _SERVICE_NAME: 'recipe-ai-service'
  _REGION: 'europe-west2'
  _ARTIFACT_REGISTRY_REPO: 'recipe-ai'

# Use faster machine type for builds
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout after 20 minutes
timeout: '1200s'
